version: '3.7'
services:
  py3o-fusion:
    image: xcgd/py3o:1.0.0
    container_name: py3o-fusion
    hostname: py3o-fusion.docker.internal
    ports:
      - "8765:8765"
    networks:
      default:
        ipv4_address: 172.18.0.30
networks:
  default:
    external: true
    name: common-net